[package]
name = "sqllogictest"
version = "0.1.0"
edition = "2021"
description = "Sqllogictest parser and runner."
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
itertools = "0.10"
tempfile = "3"
thiserror = "1"
